cp ~/memory-surprisal/code/study1/figures/decay.pdf figures/
cp ~/memory-surprisal/code/study1/figures/memory.pdf figures/
cp ~/memory-surprisal/code/study1/figures/add-surp.pdf figures/
cp ~/memory-surprisal/code/study1/figures/lower-mem.pdf figures/
cp ~/memory-surprisal/code/study1/figures/listener-tradeoff.pdf figures/
cp ~/memory-surprisal/code/study1/figures/toy-mis.pdf figures/
cp ~/memory-surprisal/code/study1/figures/toy-t-mis.pdf figures/
cp ~/memory-surprisal/code/study1/figures/toy-mem-surp.pdf figures/
cp ~/memory-surprisal/code/analysis/visualize_neural/figures/surprisal-branching-entropy-REAL.pdf figures/
cp ~/memory-surprisal/code/analysis/visualize_neural/figures/full-GROUND-listener-surprisal-memory-HIST_z_byMem_onlyWordForms_boundedVocab.pdf figures/
cp ~/memory-surprisal/code/order-freedom/infostruc/analysis/visualize_neural/figures/Czech-PDT-listener-surprisal-memory-MEDIANS_onlyWordForms_boundedVocab.pdf figures/
cp ~/memory-surprisal/writeup/quantiles-table.pdf .
cp ~/memory-surprisal/writeup/auc-table.pdf .
cp ~/memory-surprisal/writeup/auc-table_MLE.pdf .
cp ~/memory-surprisal/writeup/it-table.pdf .
cp ~/memory-surprisal/writeup/it-table-mle.pdf .
cp ~/memory-surprisal/writeup/results-table.pdf .
cp ~/memory-surprisal/writeup/results-table-mle.pdf .
cp ~/memory-surprisal/code/study3/Japanese/tradeoffs/figures/* figures/
cp ~/memory-surprisal/code/study3/Sesotho/tradeoffs/figures/* figures/
cp ~/memory-surprisal/code/analysis/visualize_neural/figures/surprisal-branching-entropy-REAL*.pdf figures/
cp ~/memory-surprisal/code/order-freedom/infostruc/analysis/medians/auc/figures/* figures/

